### ISSUE TITLE
CommonLogFactoryExtensions.UseCommonLogging couse StackOverflow

### ISSUE THREAD

**Issue by zaytsevvla** [Nicholi/Owin.Logging.Common#1]
UseCommonLogging(this IAppBuilder app, Func<ILog, TraceEventType, bool> isLogEventEnabledFunc)
and 
UseCommonLogging(this IAppBuilder app, Action<ILog, TraceEventType, String, Exception> writeLogEventFunc)
call them themselves

**Comment by nicholi** [comment]
Yikes, that was an oversight.
